openapi: "3.0.2"
info:
  title: STUN SOLUTION
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
security:
  - BearerAuth: []
servers:
  - url: http://localhost:5000
tags:
  - name: Endpoint
    description: For api endpoint documentation

paths:
  /kms:
    post:
      tags:
        - Endpoint
      summary: for GUEST
      requestBody:
        content:
          application/json:
            example:
              example:
                <array>:
                  umur_bulan: 1
                  jenis_kelamin: L
                  berat_badan: 3.5
                  tinggi_badan: 20
                  lingkar_kepala: 10
              rule:
                <array>:
                  umur_bulan: integer
                  jenis_kelamin: enum:L,P
                  berat_badan: float
                  tinggi_badan: float
                  lingkar_kepala: float
      responses:
        200:
          description: OK
          content:
            application/json:
              example:
                series:
                  - name: "Terlalu Gemuk"
                    type: "line"
                    data: ["integer"]
                  - name: "Berat Gemuk"
                    type: "line"
                    data: ["integer"]
                  - name: "Berat Normal"
                    type: "line"
                    data: ["integer"]
                  - name: "Berat Baik"
                    type: "line"
                    data: ["integer"]
                  - name: "Berat Normal"
                    type: "line"
                    data: ["integer"]
                  - name: "Berat Kurus"
                    type: "line"
                    data: ["integer"]
                  - name: "Terlalu Kurus, butuh penanganan"
                    type: "line"
                    data: ["integer"]
                  - name: "Berat bayi"
                    type: "line"
                    data: ["integer"]

  /check-up:
    post:
      tags:
        - Endpoint
      summary: for GUEST
      requestBody:
        content:
          application/json:
            example:
              example:
                umur_bulan: 12
                jenis_kelamin: L
                berat_badan: 10
                tinggi_badan: 50
                lingkar_kepala: 45
              rule:
                umur_bulan: integer
                jenis_kelamin: enum:L,P
                berat_badan: float
                tinggi_badan: float
                lingkar_kepala: float
      responses:
        200:
          description: OK
          content:
            application/json:
              example:
                head_circumference: string,
                height: string,
                id: integer,
                recomendation: text,
                weight: string
  /check-up/{id}/product:
    get:
      tags:
        - Endpoint
      summary: for GUEST
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
      responses:
        200:
          description: OK
          content:
            application/json:
              example:
                <array>:
                  id: 2
                  name: "Nutrilon 3"
                  energi_kcal: float
                  folate_ug: float
                  gula_g: float
                  kalsium_mg: float
                  lemak_g: float
                  magnesium_mg: float
                  omega_3_mg: float
                  omega_6_mg: float
                  protein_g: float
                  vitamin_a_ug: float
                  vitamin_c_mg: float
                  vitamin_d_ug: float
                  zat_besi_mg: float
                  zinc_mg: float
